#
# gradle/libs.versions.toml
#
# Version catalog
#

[versions]
kotlinx-coroutines = "1.9.0"

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }